blank_issues_enabled: false
contact_links:
  - name: 💬  Ask a question
    url: https://discord.gg/m9WHwAD
    about: Bexwing uses Discord as it's main communication platform. Here, you can hang out and chat with others, and also get support with the server! Feel free to join! We're looking forward to having you!